name: Build Windows Arm64

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      vma-native-artifact:
        value: ${{ jobs.build.outputs.vma-native-artifact }}
      D3D12MA-native-artifact:
        value: ${{ jobs.build.outputs.D3D12MA-native-artifact }}

jobs:
  build:
    runs-on: windows-11-arm
    outputs:
      vma-native-artifact: ${{ steps.vma-native.outputs.artifact-id }}
      D3D12MA-native-artifact: ${{ steps.D3D12MA-native.outputs.artifact-id }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Dotnet Restore
        run: dotnet restore
      - name: Init
        shell: pwsh
        run: ./init.ps1
      - name: Build
        shell: pwsh
        run: ./build_native.ps1
      - name: Pack VMA
        shell: pwsh
        run: ./Native/buid_vma-win-arm64.ps1
      - name: Pack D3D12MA
        shell: pwsh
        run: ./Native/buid_d3d12ma-win-arm64.ps1
      - id: vma-native
        uses: actions/upload-artifact@v4
        with:
          name: 'vma-win-arm64'
          path: ./Native/packages/GpuMemoryAllocator.vma.*.nupkg
          overwrite: true
      - id: D3D12MA-native
        uses: actions/upload-artifact@v4
        with:
          name: 'D3D12MA-win-arm64'
          path: ./Native/packages/GpuMemoryAllocator.D3D12MA.*.nupkg
          overwrite: true
